[versions]
boosted-yaml = "1.3.7"
paper-api = "1.21.11-R0.1-SNAPSHOT"
bstats = "3.1.0"
guice = '7.0.0'
lombok = "8.10.2"
folia-api = "1.21.11-R0.1-SNAPSHOT"

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

[libraries]
boosted-yaml = { module = "dev.dejvokep:boosted-yaml", version.ref = "boosted-yaml" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
folia-api = { module = "dev.folia:folia-api", version.ref = "folia-api" }